### ISSUE TITLE
Download logos from Liquipedia

### ISSUE THREAD

**Issue by manshurtigh** [buxxi/MMM-Liquipedia-Matches#6]
Hi!

I love this module. Thank you so much for creating it!

When I try to download logos for teams it only downloads "burdenunited.png" and stops after that.

![2023-07-27 23_39_48-2023-07-27 23_38_27-Portainer _ AG5-SRV-01 - Remote png ‎- Photos](https://github.com/buxxi/MMM-Liquipedia-Dota2/assets/11875063/4f87d950-c1cb-446f-9061-34a4db476550)

Am I doing anything wrong?

**Comment by buxxi** [comment]
The script should work now again, Liquipedia changed the css classname for the icons

**Comment by manshurtigh** [comment]
Works great! Thanks!
